round_1_matchups = [
    ("Gonzaga", "Georgia St"),
    ("Boise St", "Memphis"),
    ("Connecticut", "New Mexico St"),
    ("Arkansas", "Vermont"),
    ("Alabama", "Notre Dame"),
    ("Texas Tech", "Montana St"),
    ("Michigan St", "Davidson"),
    ("Duke", "CS Fullerton"),
    ("Baylor", "Norfolk St"),
    ("North Carolina", "Marquette"),
    ("St Mary's CA", "Indiana"),
    ("UCLA", "Akron"),
    ("Texas", "Virginia Tech"),
    ("Purdue", "Yale"),
    ("Murray St", "San Francisco"),
    ("Kentucky", "St Peter's"),
    ("Arizona", "Wright St"),
    ("Seton Hall", "TCU"),
    ("Houston", "UAB"),
    ("Illinois", "Chattanooga"),
    ("Colorado St", "Michigan"),
    ("Tennessee", "Longwood"),
    ("Ohio St", "Loyola-Chicago"),
    ("Villanova", "Delaware"),
    ("Kansas", "TX Southern"),
    ("San Diego St", "Creighton"),
    ("Iowa", "Richmond"),
    ("Providence", "S Dakota St"),
    ("LSU", "Iowa St"),
    ("Wisconsin", "Colgate"),
    ("USC", "Miami FL"),
    ("Auburn", "Jacksonville St")
]
first_four = [
    ("Wright St", "Bryant"),
    ("Indiana", "Wyoming"),
    ("Rutgers", "Notre Dame"),
    ("TX Southern", "TAM C. Christi")
]